FROM ubuntu:20.04

# env variables for tzdata install
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Vancouver

RUN apt-get update -y && \
    apt-get install -y \
        libeigen3-dev \
        liborocos-kdl-dev \
        libkdl-parser-dev \
        liburdfdom-dev \
        libnlopt-dev \
        libnlopt-cxx-dev \
        swig \
        python3-dev \
        python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Install repo
RUN mkdir -p tracikpy
COPY [ ".",  "tracikpy/" ]
WORKDIR tracikpy
RUN python3 -m pip install --no-cache-dir --verbose .[test]
CMD pytest .